name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "**/CONTRIBUTING.md"
      - "**/CONTRIBUTORS.txt"
      - '**/CODE_OF_CONDUCT.md'
      - "**/LICENSE"
      - "**/CODEOWNERS"
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "maven"

      - name: Check Style Guide
        run: mvn -T 1C spotless:check

      - name: Compile with Maven
        run: mvn -T 1C clean generate-sources compile --file pom.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: target/
          compression-level: 0
          if-no-files-found: error

  test:
    runs-on: ubuntu-latest
    needs:
        - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "maven"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: target/

      - name: Test with Maven
        run: mvn -T 1C test-compile test --file pom.xml
